networks:
  ds_network:
    driver: bridge

services:
  api:
    container_name: ds_api
    image: ds_fastapi_good
    build:
      context: .
      dockerfile: fastapi.good.Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 8181:8000
    env_file:
      - .env
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - ds_network

  postgres:
    container_name: ds_postgres
    image: postgres:16
    ports:
      - 5151:5432
    env_file:
      - .env
    volumes:
      - ds_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ds_network

volumes:
  ds_postgres_data:
